<?xml version="1.0" encoding="UTF-8"?>
<Profile xmlns="http://soap.sforce.com/2006/04/metadata">
    <classAccesses>
        <apexClass>DOL_DynamicPortalArticlesRenderer_Apex</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <custom>true</custom>
    <fieldPermissions>
        <editable>false</editable>
        <field>Portal_Article__c.Article_Body__c</field>
        <readable>false</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>false</editable>
        <field>Portal_Article__c.Article_Content_Type__c</field>
        <readable>false</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>false</editable>
        <field>Portal_Article__c.Article_Link_URL__c</field>
        <readable>false</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>false</editable>
        <field>Portal_Article__c.Article_Status__c</field>
        <readable>false</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>false</editable>
        <field>Portal_Article__c.Article_Sub_description__c</field>
        <readable>false</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>false</editable>
        <field>Portal_Article__c.Article_Title__c</field>
        <readable>false</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>false</editable>
        <field>Portal_Article__c.Article_body_sections_to_display__c</field>
        <readable>false</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>false</editable>
        <field>Portal_Article__c.Display_Page__c</field>
        <readable>false</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>false</editable>
        <field>Portal_Article__c.External_Id__c</field>
        <readable>false</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>false</editable>
        <field>Portal_Article__c.Internal_Article_Redirection__c</field>
        <readable>false</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>false</editable>
        <field>Portal_Article__c.Order_of_Display__c</field>
        <readable>false</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>false</editable>
        <field>Portal_Article__c.Parent_Article__c</field>
        <readable>false</readable>
    </fieldPermissions>
    <layoutAssignments>
        <layout>Portal_Article__c-Portal Article Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Portal_Article__c-Portal Article Layout</layout>
        <recordType>Portal_Article__c.Body</recordType>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Portal_Article__c-Portal Article Layout</layout>
        <recordType>Portal_Article__c.Footer</recordType>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Portal_Article__c-Portal Article Layout</layout>
        <recordType>Portal_Article__c.Header</recordType>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Portal_Article__c-Portal Article Layout</layout>
        <recordType>Portal_Article__c.Main</recordType>
    </layoutAssignments>
    <recordTypeVisibilities>
        <default>false</default>
        <recordType>Portal_Article__c.Body</recordType>
        <visible>false</visible>
    </recordTypeVisibilities>
    <recordTypeVisibilities>
        <default>false</default>
        <recordType>Portal_Article__c.Footer</recordType>
        <visible>false</visible>
    </recordTypeVisibilities>
    <recordTypeVisibilities>
        <default>false</default>
        <recordType>Portal_Article__c.Header</recordType>
        <visible>false</visible>
    </recordTypeVisibilities>
    <recordTypeVisibilities>
        <default>false</default>
        <recordType>Portal_Article__c.Main</recordType>
        <visible>false</visible>
    </recordTypeVisibilities>
    <userLicense>Guest User License</userLicense>
    <userPermissions>
        <enabled>true</enabled>
        <name>EnableNotifications</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>PasswordNeverExpires</name>
    </userPermissions>
</Profile>
