/* [Nibedita Swain/ July 8, 2019] 
        Convert SSN to UBI – this is now out of Release 1 as it was dependent on API.so commenting out the code.
        Workaround – Send SSN instead of UBI (This is tested and verified with ASC)
        Changes – We have to revert the code and would be part of R2*/
public with sharing class Dol_ASCResponse {
    /*public DolResponse DolResponse  {get;set;}

    public class DolResponse{
        public String uid {get;set;}
    }
	
    
    public static Dol_ASCResponse parse(String json) {
            return (Dol_ASCResponse) System.JSON.deserialize(json, Dol_ASCResponse.class);
        }*/
}