@isTest
public class melissadataaddresscheckserviceTest {
 
    public static testMethod void melissadataaddresscheckserviceMethod(){
        /*test.startTest();
        melissadataaddresscheckservice.doAddressCheck_element address = new melissadataaddresscheckservice.doAddressCheck_element();
        melissadataaddresscheckservice.doAddressCheckResponse_element addressCheck = new melissadataaddresscheckservice.doAddressCheckResponse_element();
        melissadataaddresscheckservice.BasicHttpBinding_IService isService = new melissadataaddresscheckservice.BasicHttpBinding_IService();
        mdwebserviceaddress.RequestArray req = new mdwebserviceaddress.RequestArray();
        req.TransmissionReference = 't';
        req.CustomerID='t';
        public class RequestArray {
        public String TransmissionReference;
        public String CustomerID;
        public String OptAddressParsed;
        public mdwebserviceaddress.Record_element[] Record;
        private String[] TransmissionReference_type_info = new String[]{'TransmissionReference','urn:mdWebServiceAddress',null,'0','1','false'};
        private String[] CustomerID_type_info = new String[]{'CustomerID','urn:mdWebServiceAddress',null,'0','1','false'};
        private String[] OptAddressParsed_type_info = new String[]{'OptAddressParsed','urn:mdWebServiceAddress',null,'0','1','false'};
        private String[] Record_type_info = new String[]{'Record','urn:mdWebServiceAddress',null,'0','-1','false'};
        private String[] apex_schema_type_info = new String[]{'urn:mdWebServiceAddress','true','false'};
        private String[] field_order_type_info = new String[]{'TransmissionReference','CustomerID','OptAddressParsed','Record'};
    }        
          Test.setMock(HttpCalloutMock.class, new DOL_MockHttpResponse());
        isService.doAddressCheck(req);
        test.stopTest();*/
    }
}