@IsTest
public class TestUtility_Test {
	@IsTest
    public static void testUtilityMethods(){
        TestUtility.getContact();
        TestUtility.getCEnvelope();
        TestUtility.getAccount();
        TestUtility.getParcel();
        TestUtility.getInspection();
        TestUtility.getDeposit();
        TestUtility.getBusinessLicense();
        TestUtility.getApp();
        TestUtility.getLicenseApp();
    }
}