Application_Type__c ,Credential_type__c,Credential__c,Application_Method__c,musw__status__c,CreatedDate,LastModifiedDate
Manufactured Homes,Manufactured Homes Credential,Manufactured Homes Installer,Course Completion,Pending,2013-11-08T23:00:01.235-07:00,2013-11-08T23:00:01.235-07:00
Manufactured Homes,Manufactured Homes Credential,Manufactured Homes Installer,Course Completion,Active,2013-11-08T23:00:01.235-07:00,2013-11-08T23:00:01.235-07:00
