Application_Type__c,Program_Area__c,Permit_Type__c,Application_Method__c,musw__status__c,sub_status__c,CreatedDate,LastModifiedDate
Manufactured Homes Communities,Manufactured Homes Communities,Manufactured Homes Community Permit,General Application,In Review,Additional Information Required,2013-11-08T23:00:01.235-07:00,2013-11-08T23:00:01.235-07:00
Manufactured Homes Communities,Manufactured Homes Communities,Manufactured Homes Community Permit,General Application,Active,,2013-11-08T23:00:01.235-07:00,2013-11-08T23:00:01.235-07:00
